<a href="https://colab.research.google.com/github/korsanreis/segment-geospatial/blob/main/mean_reversion_strategy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating a Mean Reversion strategy

## Goal = Find a statistical pattern

![Alt text](https://i.postimg.cc/023pdYK0/BCH.png)

In [1]:
import numpy as np
import pandas as pd

In [2]:
url = "https://drive.google.com/uc?export=download&id=1eQN7nCrv1byqqX8oIt1Ks6SlDFb_ySlc"
df = pd.read_csv(url)
df

,Unnamed: 0,t,T,s,i,o,c,h,l,v,n,close_log_return,close_log_return_lag_1,close_log_return_dir,close_log_return_lag_1_dir
0,0,2022-04-13,2022-04-13 23:59:59.999,BCH,1d,304.73,340.90,349.63,301.03,0.000,0,NaN,NaN,-1,-1
1,1,2022-04-14,2022-04-14 23:59:59.999,BCH,1d,340.90,337.42,353.00,332.34,0.000,0,-0.010261,NaN,-1,-1
2,2,2022-04-15,2022-04-15 23:59:59.999,BCH,1d,337.41,340.62,345.29,333.08,0.000,0,0.009439,-0.010261,1,-1
3,3,2022-04-16,2022-04-16 23:59:59.999,BCH,1d,340.63,342.58,347.61,338.43,0.000,0,0.005738,0.009439,1,1
4,4,2022-04-17,2022-04-17 23:59:59.999,BCH,1d,342.58,327.85,348.81,327.12,0.000,0,-0.043949,0.005738,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,1456,2026-04-08,2026-04-08 23:59:59.999,BCH,1d,445.80,441.22,449.44,439.88,3051.575,4525,-0.010372,0.025075,-1,1
1457,1457,2026-04-09,2026-04-09 23:59:59.999,BCH,1d,441.11,442.73,446.27,433.03,4415.805,5588,0.003416,-0.010372,1,-1
1458,1458,2026-04-10,2026-04-10 23:59:59.999,BCH,1d,442.82,443.61,446.66,434.19,4414.799,5688,0.001986,0.003416,1,1
1459,1459,2026-04-11,2026-04-11 23:59:59.999,BCH,1d,443.56,437.32,445.06,436.27,1886.537,3916,-0.014281,0.001986,-1,1
1460,1460,2026-04-12,2026-04-12 23:59:59.999,BCH,1d,437.32,425.52,437.76,422.83,3278.733,2960,-0.027353,-0.014281,-1,-1

In [3]:
df['close_log_return'] = np.log(df['c']/df['c'].shift(1))
df

,Unnamed: 0,t,T,s,i,o,c,h,l,v,n,close_log_return,close_log_return_lag_1,close_log_return_dir,close_log_return_lag_1_dir
0,0,2022-04-13,2022-04-13 23:59:59.999,BCH,1d,304.73,340.90,349.63,301.03,0.000,0,NaN,NaN,-1,-1
1,1,2022-04-14,2022-04-14 23:59:59.999,BCH,1d,340.90,337.42,353.00,332.34,0.000,0,-0.010261,NaN,-1,-1
2,2,2022-04-15,2022-04-15 23:59:59.999,BCH,1d,337.41,340.62,345.29,333.08,0.000,0,0.009439,-0.010261,1,-1
3,3,2022-04-16,2022-04-16 23:59:59.999,BCH,1d,340.63,342.58,347.61,338.43,0.000,0,0.005738,0.009439,1,1
4,4,2022-04-17,2022-04-17 23:59:59.999,BCH,1d,342.58,327.85,348.81,327.12,0.000,0,-0.043949,0.005738,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,1456,2026-04-08,2026-04-08 23:59:59.999,BCH,1d,445.80,441.22,449.44,439.88,3051.575,4525,-0.010372,0.025075,-1,1
1457,1457,2026-04-09,2026-04-09 23:59:59.999,BCH,1d,441.11,442.73,446.27,433.03,4415.805,5588,0.003416,-0.010372,1,-1
1458,1458,2026-04-10,2026-04-10 23:59:59.999,BCH,1d,442.82,443.61,446.66,434.19,4414.799,5688,0.001986,0.003416,1,1
1459,1459,2026-04-11,2026-04-11 23:59:59.999,BCH,1d,443.56,437.32,445.06,436.27,1886.537,3916,-0.014281,0.001986,-1,1
1460,1460,2026-04-12,2026-04-12 23:59:59.999,BCH,1d,437.32,425.52,437.76,422.83,3278.733,2960,-0.027353,-0.014281,-1,-1

## Create Auto-Regressive Log Returns

In [4]:
df['close_log_return_lag_1'] = df['close_log_return'].shift()
df

,Unnamed: 0,t,T,s,i,o,c,h,l,v,n,close_log_return,close_log_return_lag_1,close_log_return_dir,close_log_return_lag_1_dir
0,0,2022-04-13,2022-04-13 23:59:59.999,BCH,1d,304.73,340.90,349.63,301.03,0.000,0,NaN,NaN,-1,-1
1,1,2022-04-14,2022-04-14 23:59:59.999,BCH,1d,340.90,337.42,353.00,332.34,0.000,0,-0.010261,NaN,-1,-1
2,2,2022-04-15,2022-04-15 23:59:59.999,BCH,1d,337.41,340.62,345.29,333.08,0.000,0,0.009439,-0.010261,1,-1
3,3,2022-04-16,2022-04-16 23:59:59.999,BCH,1d,340.63,342.58,347.61,338.43,0.000,0,0.005738,0.009439,1,1
4,4,2022-04-17,2022-04-17 23:59:59.999,BCH,1d,342.58,327.85,348.81,327.12,0.000,0,-0.043949,0.005738,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,1456,2026-04-08,2026-04-08 23:59:59.999,BCH,1d,445.80,441.22,449.44,439.88,3051.575,4525,-0.010372,0.025075,-1,1
1457,1457,2026-04-09,2026-04-09 23:59:59.999,BCH,1d,441.11,442.73,446.27,433.03,4415.805,5588,0.003416,-0.010372,1,-1
1458,1458,2026-04-10,2026-04-10 23:59:59.999,BCH,1d,442.82,443.61,446.66,434.19,4414.799,5688,0.001986,0.003416,1,1
1459,1459,2026-04-11,2026-04-11 23:59:59.999,BCH,1d,443.56,437.32,445.06,436.27,1886.537,3916,-0.014281,0.001986,-1,1
1460,1460,2026-04-12,2026-04-12 23:59:59.999,BCH,1d,437.32,425.52,437.76,422.83,3278.733,2960,-0.027353,-0.014281,-1,-1

## Encode Direction

* 1 => Long => Bet Up
* -1 => Short => Bet Down

In [5]:
for col in ['close_log_return','close_log_return_lag_1']:
  df[f'{col}_dir'] = df[col].map(lambda x: 1 if x>0 else -1)
df

,Unnamed: 0,t,T,s,i,o,c,h,l,v,n,close_log_return,close_log_return_lag_1,close_log_return_dir,close_log_return_lag_1_dir
0,0,2022-04-13,2022-04-13 23:59:59.999,BCH,1d,304.73,340.90,349.63,301.03,0.000,0,NaN,NaN,-1,-1
1,1,2022-04-14,2022-04-14 23:59:59.999,BCH,1d,340.90,337.42,353.00,332.34,0.000,0,-0.010261,NaN,-1,-1
2,2,2022-04-15,2022-04-15 23:59:59.999,BCH,1d,337.41,340.62,345.29,333.08,0.000,0,0.009439,-0.010261,1,-1
3,3,2022-04-16,2022-04-16 23:59:59.999,BCH,1d,340.63,342.58,347.61,338.43,0.000,0,0.005738,0.009439,1,1
4,4,2022-04-17,2022-04-17 23:59:59.999,BCH,1d,342.58,327.85,348.81,327.12,0.000,0,-0.043949,0.005738,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,1456,2026-04-08,2026-04-08 23:59:59.999,BCH,1d,445.80,441.22,449.44,439.88,3051.575,4525,-0.010372,0.025075,-1,1
1457,1457,2026-04-09,2026-04-09 23:59:59.999,BCH,1d,441.11,442.73,446.27,433.03,4415.805,5588,0.003416,-0.010372,1,-1
1458,1458,2026-04-10,2026-04-10 23:59:59.999,BCH,1d,442.82,443.61,446.66,434.19,4414.799,5688,0.001986,0.003416,1,1
1459,1459,2026-04-11,2026-04-11 23:59:59.999,BCH,1d,443.56,437.32,445.06,436.27,1886.537,3916,-0.014281,0.001986,-1,1
1460,1460,2026-04-12,2026-04-12 23:59:59.999,BCH,1d,437.32,425.52,437.76,422.83,3278.733,2960,-0.027353,-0.014281,-1,-1

## Study Price Movements

In [6]:
df.groupby('close_log_return_lag_1_dir').aggregate({'close_log_return':['mean','count','sum']})

                           close_log_return
                                       mean count       sum
close_log_return_lag_1_dir
-1                                 0.002264   735  1.664161
 1                                -0.001990   725 -1.442438

## Out of Sample Validation

In [7]:
in_sample

NameError: name 'in_sample' is not defined

In [ ]:
out_sample

In [ ]:
in_sample.groupby('close_log_return_lag_1_dir').aggregate({'close_log_return':['mean','count','sum']})

In [ ]:
out_sample.groupby('close_log_return_lag_1_dir').aggregate({'close_log_return':['mean','count','sum']})

## Display Equity Curve

In [ ]:
df['signal'] = -1 * df['close_log_return_lag_1_dir']
df

In [ ]:
df['trade_log_return'] = df['signal'] * df['close_log_return']
df

In [ ]:
df['trade_log_return'].cumsum().plot()

## Strategy Statistics

Win Rate

In [ ]:
df['is_won'] = df['trade_log_return'] > 0
df['is_won'].mean()

Total Gross Compound Return

In [ ]:
r = np.exp(df['trade_log_return'].sum()) - 1
r

In [ ]:
12 * r

Annualized Sharpe

In [ ]:
df['trade_log_return'].mean() / df['trade_log_return'].std() * np.sqrt(365)

Exercises

1. Add round-trip transaction fees
2. Display equity fee in $ with fees included
3. Add trade notional value.